language: node_js
node_js:
  - 12
script: npm run build
branches:
  only:
    - master
    - staging
deploy:
  - provider: pages
    skip_cleanup: true
    github_url: github.com
    github_token: $GITHUB_TOKEN
    repo: ibm-garage-cloud/ibm-garage-developer-guide-staging
    keep_history: false
    local_dir: public
    on:
      branch: staging
  - provider: pages
    skip_cleanup: true
    github_url: github.com
    github_token: $GITHUB_TOKEN
    fqdn: cloudnativetoolkit.dev
    keep_history: false
    local_dir: public
    on:
      branch: master
